# Generated by Django 3.1.4 on 2021-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('mark', models.IntegerField()),
                ('passdate', models.DateField()),
                ('admdate', models.DateTimeField()),
            ],
        ),
    ]
