# Generated by Django 3.1.4 on 2021-05-01 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='onepage',
            fields=[
                ('creater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('pagename', models.CharField(max_length=64)),
                ('pagecatagory', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='likethepage',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_relationship.onepage')),
                ('like', models.IntegerField()),
            ],
            bases=('model_relationship.onepage',),
        ),
        # migrations.CreateModel(
        #     name='song',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('song_name', models.CharField(max_length=64)),
        #         ('song_duration', models.IntegerField()),
        #         ('singer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        migrations.CreateModel(
            name='manypage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=64)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
