# Generated by Django 3.1.4 on 2021-05-01 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_relationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=64)),
                ('song_duration', models.IntegerField()),
                ('singer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
